apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pv
spec:
  awsElasticBlockStore:
    volumeID: <voulume_id>
    fsType: xfs
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 4Gi
  hostPath:
    path: '/home/ubuntu/'
