apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["bash", "-c",  "sleep 10"]
      restartPolicy: Never
